[install]
peer = true
optional = true
dev = true
saveTextLockfile = true
registry = "https://registry.npmjs.org"
cache = true

[workspaces]
packages = ["apps/*", "packages/*"]

[test]
root = "./"
coverage = true
